### ISSUE TITLE
Method not found: 'Void DNSimple.DNSimpleRestClient..ctor(System.String, System.String, System.String)',

### ISSUE THREAD

**Issue by mcantor** [dwdii/DNScymbal#3]
I just upgraded to the most recent version, and I now get this dialog box with the title "DNScymbal Updater". I'm on Windows 7 SP1.

**Comment by dwdii** [comment]
Hi Max! I've seen that before, and thought it was fixed... but maybe not. Did you uninstall the old version before installing the new version? That might help. Basically, I think one of the dependency DLLs is not being updated during the upgrade, but if you uninstall first, as I recall, the new version installer would deploy the dependent DLL correctly. 

Here is a screenshot of what the program folder should look like:

![dnscymbalprogfiles](https://cloud.githubusercontent.com/assets/915859/6013236/d83957e0-ab1f-11e4-9ede-7dbe92003622.png)

**Comment by dwdii** [comment]
Here are the versions of those DLLs. If needed, you could get them from the repository:

[DNSimple.Api.dll](https://github.com/dwdii/DNScymbal/blob/master/packages/DNSimple.0.5.0/lib/4.0/DNSimple.Api.dll) - v1.0.0.0
[JsonFx.dll](https://github.com/dwdii/DNScymbal/blob/master/packages/DNSimple.0.5.0/lib/4.0/JsonFx.dll) - v2.0.1106.2610
[Newtonsoft.Json.dll](https://github.com/dwdii/DNScymbal/tree/master/packages/Newtonsoft.Json.4.0.5) - v4.0.5.14411
[RestSharp.dll](https://github.com/dwdii/DNScymbal/tree/master/packages/RestSharp.102.6) - 102.5.0.0

Sorry for the inconvenience,

Daniel

**Comment by dwdii** [comment]
Again, sorry for the inconvenience. Hope the previously mentioned suggestions helped resolve the issue!
